name: authwebview
description: A Flutter package for OAuth authentication using WebView.
version: 1.0.5
homepage: https://github.com/hakanmertb/authwebview

environment:
  sdk: ^3.5.0
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  http: ^1.2.2
  webview_flutter: ^4.0.0
  crypto: ^3.0.1
  device_info_plus: ^9.0.0
  package_info_plus: ^4.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter: